sonar.projectKey=crfradorEjercicio
sonar.projectName=crfradorEjercicio
sonar.sources=.\src
sonar.host.url=http://192.168.9.8:9100
sonar.token=sqa_ea7a3e025a2f8765e9629581f60d6f8bbf328a3a
sonar.python.version=3.10
#CONFIGURACIÓN SONAR#